[package]
name = "pi-estimator"
version = "0.1.0"
authors = ["0h-n0 <kbu94982@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-pilib = { path = '../rust-pilib', version = '*'}